#!perl

use strict;
use warnings;
use lib "lib";
use CLI::Dispatch;

CLI::Dispatch->run_directly('cli_sokoban');

package cli_sokoban;
use base 'CLI::Dispatch::Command';
use Games::Sokoban::Player;

sub options {qw/file|f=s uri|u=s/}

sub run {
  my $self = shift;

  my $data;
  if ($self->{file} && -f $self->{file}) {
    $data = do {
      open my $fh, '<', $self->{file} or die $!;
      local $/;
      <$fh>;
    };
  }
  elsif ($self->{uri}) {
    eval {
      require HTTP::Tiny;
      my $res = HTTP::Tiny->new->get($self->{uri});
      $data = $res->{content} if $res->{success};
    };
  }

  Games::Sokoban::Player->new->run(levels => $data);
}
